version: 2.0
jobs:
  build:
    docker:
      - image: clojure:alpine
    working_directory: ${HOME}/compojure-app
    steps:
      - checkout

      - restore_cache:
          keys:
            - compojure-app-jars-v1-{{ checksum "project.clj" }}

      - run:
          name: Download dependencies
          command: lein deps
          working_directory: ${HOME}/compojure-app

      - run:
          name: Run server tests
          command: lein test
          working_directory: ${HOME}/compojure-app
      - save_cache:
          key: compojure-app-jars-v1-{{ checksum "project.clj" }}
          paths:
            - ${HOME}/.m2

  deploy:
    filters:
      branches:
        only:
          - master
    docker:
      - image: google/cloud-sdk:alpine
    working_directory: ${HOME}/compojure-app
    steps:
      - checkout

      - restore_cache:
          keys:
            - compojure-app-jars-v1-{{ checksum "project.clj" }}
            - compojure-app-machine-jars-v1

      - run:
          name: Authenticate with Google Cloud
          command: |
            echo $GCLOUD_KEY_JSON > ${HOME}/gcloud-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-key.json

      - run:
          name: Deploy compojure-app to Google App Engine
          no_output_timeout: 3600
          command: |
            gcloud -q config set project ${GOOGLE_PROJECT_ID}
            gcloud -q app deploy app.yaml

      - run:
          name: discarding all changes
          command: git checkout -- .

      - save_cache:
          key: compojure-app-jars-v1-{{ checksum "project.clj" }}
          paths:
            - ${HOME}/.m2

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

